
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     Набор иконок для кнопок тулбара и меню
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


doc_edit01_gif = """
R0lGODlhEAAQAPIFAAAAAAAAAIAAAP//AIaGhv///wAAAAAAACH5BAEAAAAALAAAAAAQABAAAANMGLoLDgqWSUuEQq
hCercWEWQbQZlMoZXnGQyiZE6zNQwBIXuzCAeOQKXywul2Hs4rFhxOFMaHkIdqSJ0Wa5Masjwk2OeXQdZ+z2hHAgA7
"""


doc_edit02_gif = """
R0lGODlhEAAQAPMIAAAAAAAAAAD/AP//AAAAgAAA/4aGhv/78P///wAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAA
AALAAAAAAQABAAAARUEMhJqyQ4Zwu0l0EwEUdpHgQQCILYoR62ttdRFASOB0jrkgUTAmEIDIojm60wNA4ChlFOWDy6
KMEbwgm1BE1GpCWXKxi7HEromgaxKQhAPC5o2ykRADs=
"""

doc_new_gif = """
R0lGODlhEAAQAPIEAAAAAAAAAP//AIaGhv///wAAAAAAAAAAACH5BAEAAAAALAAAAAAQABAAAANDKACjHHDJxggThE
R5W8uaxgnfYA6hyJiEgIFQLBEoDd4Bs3w3ztU9GCcQ9EmIxUzumFQOm6oFMrmUQquAmHbL6XoXCQA7
"""


doc_new01_gif = """
R0lGODlhEAAQAPEDAAAAAAAAgICAgP///yH5BAEAAAAALAAAAAAQABAAAAI1hI95wc1qwpj0KUmnDDfrlmCZQAYCIn
qDiarVubgaHMkrDaQeG8t87cM5hgwcgIRMkiDMQwEAOw==
"""


placeholder_gif = """
R0lGODlhEAAQAPAAAAAAAAAAACH5BAEAAAAALAAAAAAQABAAAAIOhI+py+0Po5y02ouzPgUAOw==
"""

row_add_gif = """
R0lGODlhEAAQAPEAAAAAAIAAAAAAgKqqqiH5BAEAAAAALAAAAAAQABAAAAI0hI+pm8EbnBIqSkMzsheIP2yc95VCCH
ADWq6Hta7nHKdBjHq14exGCES4FLlD8YFMKpeAAgA7
"""


row_drop_gif = """
R0lGODlhEAAQAPEAAAAAAIAAAIaGhqqqqiH5BAEAAAAALAAAAAAQABAAAAJAhI+pGnG+RBPCNCBhpmOA5lBgwHXDCA
wZaXqj85oWqE6ZNwedfZKPXmN1JDjHjiSQsQ67Eo7DZMqkiil1gc0uCgA7
"""


save0_gif = """
R0lGODlhEAAQAPIAAAAAAD4+Prm5AJ6env/78AAAAAAAAAAAACH5BAEAAAAALAAAAAAQABAAAANBCLrcGjDKuIIIJG
uCw3jXpkXDZ2Eid5XAmaqeGaYn69KrfE1W3grAoNDX40GIwEmmplPCWC2jBAooWa9XBnY7SAAAOw==
"""


save1_gif = """
R0lGODlhEAAQAPIAAAAAAAAAALm5AKqqqv/78AAAAAAAAAAAACH5BAEAAAAALAAAAAAQABAAAANBGLrMAEEEQiud4c
Vp6xrD1nkSKI7EZkpoWoYsqsJSowhvhO88Hqw120xnu+R8DeOPVnQtIcIG6AGqWq8PwHULSgAAOw==
"""



