# Generated by Django 5.1.4 on 2025-01-24 17:28

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_options_newspost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[news.models.validate_positive], verbose_name='Высота картинки'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[news.models.validate_positive], verbose_name='Ширина картинки'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
