# Generated by Django 5.2 on 2025-05-05 11:17

from django.db import migrations

def add_order_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('main', 'OrderStatus')
    statuses = ['Новый', 'В работе', 'Доставка', 'Выполнен']
    for status in statuses:
        OrderStatus.objects.get_or_create(name=status)

def remove_order_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('main', 'OrderStatus')
    OrderStatus.objects.filter(name__in=['Новый', 'В работе', 'Доставка', 'Выполнен']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderstatus_order_orderdetail'),
    ]

    operations = [
        migrations.RunPython(add_order_statuses, remove_order_statuses),
    ]
