# Generated by Django 5.2 on 2025-05-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orderreview_productrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Подробная информация о заказе', 'verbose_name_plural': 'Подробная информация о заказе'},
        ),
        migrations.AlterModelOptions(
            name='orderreview',
            options={'verbose_name': 'Отзывы покупателя', 'verbose_name_plural': 'Отзывы покупателя'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name': 'Оценка продукта', 'verbose_name_plural': 'Оценка продукта'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
