# Generated by Django 5.2 on 2025-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_options_alter_orderdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Статус'),
        ),
    ]
