# Generated by Django 5.2 on 2025-05-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_orderstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отчета')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма продаж')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибыль')),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расходы')),
                ('sales_data', models.JSONField(blank=True, null=True, verbose_name='Данные по продажам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчета')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отчеты по продажам',
                'verbose_name_plural': 'Отчеты по продажам',
            },
        ),
    ]
