# Generated by Django 5.1.4 on 2025-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Краткое описание фильма')),
                ('review', models.TextField(verbose_name='Отзыв о фильме')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
