
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345++
    ports:
      - "5050:80"
    volumes:
      - ~/PgAdmin/data:/var/lib/pgadmin
    networks:
      - custom_network_x1

networks:
  custom_network_x1:


